{
 "title": "Sensors",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Raspberry Temp",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "node_hwmon_temp_celsius{instance=\"\"}",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 2, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "bme280_temp" }
   ]
  },
  {
   "title": "Delta T",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 2, "x": 7, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max_over_time(bme280_temp[1d]) - min_over_time(bme280_temp[1d])",
     "legendFormat": "bme280"
    }
   ]
  },
  {
   "title": "CO2",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 2, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "mh_z19_co2{location=\"box\"}"
    }
   ]
  },
  {
   "title": "humidity",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 2, "x": 11, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "bme280_humidity" }
   ]
  },
  {
   "title": "humidity drying",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 2, "x": 22, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "bme280_humidity" }
   ]
  },
  {
   "title": "Temperature",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    { "expr": "bme280_temp", "legendFormat": "bme280" }
   ]
  },
  {
   "title": "CO2",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "ppm" }
   ],
   "targets": [
    { "expr": "mh_z19_co2", "legendFormat": "{{location}}" }
   ]
  },
  {
   "title": "Delta T",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "max_over_time(bme280_temp[1d]) - min_over_time(bme280_temp[1d])",
     "legendFormat": "1d"
    },
    {
     "expr": "max_over_time(bme280_temp[3d]) - min_over_time(bme280_temp[3d])",
     "legendFormat": "3d"
    },
    {
     "expr": "max_over_time(bme280_temp[5d]) - min_over_time(bme280_temp[5d])",
     "legendFormat": "5d"
    },
    {
     "expr": "max_over_time(bme280_temp[7d]) - min_over_time(bme280_temp[7d])",
     "legendFormat": "7d"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "humidity" }
   ],
   "targets": [
    { "expr": "bme280_humidity", "legendFormat": "bme280_humidity" }
   ]
  },
  {
   "title": "Pressure",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "pressurehpa" }
   ],
   "targets": [
    { "expr": "bme280_pressure", "legendFormat": "bme280_pressure" }
   ]
  }
 ]
}